project:
  type: website
  output-dir: docs
  render:    #白名单
    - index.qmd
    - assignments/assignment_1/census_quality.qmd
    - assignments/assignment_2/assignment2_Zicheng_Xiang.qmd
    - assignments/assignment_3/Yang_Chen_Fang_Gao_Xiang_Zhao_Appendix.qmd
    - assignments/assignment_3/Yang_Chen_Fang_Gao_Xiang_Zhao_Presentation.qmd
    - assignments/assignment_4/Assignment4_Spatial_Predictive_Analysis.qmd
    - assignments/assignment_5/assignment5.rmd
    - assignments/final_project_analysis_process/eviction_data_analysis.rmd
    - assignments/final_project_presentation/eviction_presentation.qmd

website:
  title: "Your Name - Zicheng Xiang MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Weekly Notes
        menu:
          - href: weekly-notes/week-01-notes.html
            text: Weekly Notes 1
          - href: weekly-notes/week-02-notes.html
            text: Weekly Notes 2
          - href: weekly-notes/week-03-notes.html
            text: Weekly Notes 3
          - href: weekly-notes/week-04-notes.html
            text: Weekly Notes 4
          - href: weekly-notes/week-05-notes.html
            text: Weekly Notes 5
          - href: weekly-notes/week-06-notes.html
            text: Weekly Notes 6
          - href: weekly-notes/week-07-notes.html
            text: Weekly Notes 7
          - href: weekly-notes/week-09-notes.html
            text: Weekly Notes 9
          - href: weekly-notes/week-10-notes.html
            text: Weekly Notes 10
      - text: Assignments
        menu:
          - href: assignments/assignment_1/census_quality.qmd
            text: "Assignment 1: Census Data Exploration"  
          - href: assignments/assignment_2/assignment2_Zicheng_Xiang.qmd
            text: "Assignment 2: Spatial Analysis and Visualization"  
          - href: assignments/assignment_3/Yang_Chen_Fang_Gao_Xiang_Zhao_Appendix.qmd
            text: "Assignment 3: Midterm Appendix"
          - href: assignments/assignment_3/Yang_Chen_Fang_Gao_Xiang_Zhao_Presentation.qmd
            text: "Assignment 3: Midterm Presentation"  
          - href: assignments/assignment_4/Assignment4_Spatial_Predictive_Analysis.qmd
            text: "Assignment 4: Spatial Predictive Analysis"  
          - href: assignments/assignment_5/assignment5.rmd
            text: "Assignment 5: Space-Time Prediction of Bike Share Demand: Philadelphia Indego" 
          - href: assignments/final_project_analysis_process/eviction_data_analysis.rmd
            text: "Final Project Analysis" 
          - href: assignments/final_project_presentation/eviction_presentation.qmd
            text: "Final Project Presentation" 

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
